### ISSUE TITLE
[BUG] period>120 causes component to not run/initialize

### ISSUE THREAD

**Issue by Cyber5imon** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#24]
| Software | Version |
| --- | --- |
| Home Assistant | v0.115.6 |
| sensor.goveetemp_bt_hci | v0.7.1 |

When setting the `period` to anything greater than 120, the component won't run. The only output in the log (with debug) is:
`2020-10-08 13:20:58 DEBUG (SyncWorker_0) [custom_components.govee_ble_hci.sensor] Starting Govee HCI Sensor`

Anything 120 or less works fine...

```
sensor:
  - platform: govee_ble_hci
    period: 121 # >120 Causes Component to Break
    govee_devices:
```
