### ISSUE TITLE
No more than 3 devices

### ISSUE THREAD

**Issue by hazmateod** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#43]
When I add a 4th devices it gives me an error in the config yaml

  govee_devices:
          - mac: "E3:60:58:E1:91:03"
            name: NetworkCab
          - mac: "A4:C1:38:FC:FE:81"
            name: Bathroom
          - mac: "A4:C1:38:69:57:1A"
            name: NorthLivingRm

**Comment by Thrilleratplay** [comment]
YAML is a significant whitespace language, meaning the whitespace indentation is important to its validity.  I believe your issue is not the number of devices but the whitespaced used to add a fourth device is ether tabs or the wrong number of spaces.

```
govee_devices:
  - mac: "E3:60:58:E1:91:03"
    name: NetworkCab
  - mac: "A4:C1:38:FC:FE:81"
    name: Bathroom
  - mac: "A4:C1:38:69:57:1A"
    name: NorthLivingRm
  - mac: "XX:YY:ZZ:12:34:56"
    name: SomeName
```

To save time and patience, Google "YAML linter online", then copy and patse online.  Most will validate changes in real time.

Hopefully this correct your issue.but,  as stated in the README, this should have been asked on [this component's Home Assistant community post](https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696).  I am going to close this issue.
